Update coverage.yml

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -34,5 +34,8 @@ jobs:
       with:
         report-only-changed-files: true
         coverage-path: ./coverage.txt
+    # Jest does exit with a 0 exit code even if the tests fails
     - run: |
-        echo ${{steps.coverage.outputs.lines}}
+        if [${{steps.coverage.outputs.lines}} -eq 0 ]; then
+          exit 1;
+        fi
